version: "3.9"

services:
  frontend:
    build: ./DockerFrontend
    ports:
      - "3000:3000"   # Only frontend exposed
    depends_on:
      - backend

  backend:
    build: ./Backend
    expose:
      - "3001"        # Only exposed to other containers
    env_file:
      - .env
    volumes:
      - ./backend/uploads:/app/uploads